name: versus_deum_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.15.0
  get: 4.3.8
  get_it: ^7.2.0
  google_sign_in: ^5.2.0
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  kt_dart: ^0.9.1
  uuid: ^3.0.5

dev_dependencies:
  analyzer: ^2.3.0
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  json_serializable: ^5.0.2
  lint: ^1.7.2

flutter:
  uses-material-design: true
