name: versus_deum_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.15.0
  get: 4.3.8
  google_sign_in: ^5.2.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  lints: 1.0.1

flutter:
  uses-material-design: true
